# Generated by Django 4.0.4 on 2022-05-27 23:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('school_name', models.CharField(max_length=20)),
                ('max_students', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('student_firstname', models.CharField(max_length=20)),
                ('student_lastname', models.CharField(max_length=20)),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student_school.schools')),
            ],
        ),
    ]
