# Generated by Django 4.0.4 on 2022-05-28 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student_school', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='school_id',
            new_name='school',
        ),
    ]
